name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
    - name: Deploy to Azure Storage      
      uses: TravisSpomer/deploy-to-azure-storage@v1
      with:
        # The location of your built site files. (For example, "out".)
        source-path: ./_site
        # A SAS URL for your storage account. (You should store this in a Secret.)
        sas-url: ${{ secrets.AZURE_STORAGE_WEB }}
