name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
    - name: Deploy to Azure Storage
      # You may pin to the exact commit or the version.
      # uses: TravisSpomer/deploy-to-azure-storage@7e8d16a2515d37e722d32caf382bd6f4a258d4e3
      uses: TravisSpomer/deploy-to-azure-storage@v1
      with:
        # The location of your built site files. (For example, "out".)
        source-path: ./_site
        # A SAS URL for your storage account. (You should store this in a Secret.)
        sas-url: https://luisdelstatic.blob.core.windows.net/?sv=2019-12-12&ss=bfqt&srt=co&sp=rwdlacupx&se=2025-09-20T00:43:47Z&st=2020-09-19T16:43:47Z&spr=https&sig=Ko%2Fk1AfEU1GCo71aFaW8CtpnJMoTd3RRBbxXODYlTUA%3D
